
export const REGISTER_USER="REGISTER_USER";
export const REGISTER_USER_START="REGISTER_USER_START";
export const REGISTER_USER_FAIL="REGISTER_USER_FAIL";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";

export const LOGIN_USER_START="LOGIN_USER_START";
export const LOGIN_USER_FAIL="LOGIN_USER_FAIL";
export const SET_CURRENT_USER="SET_CURRENT_USER";

export const GET_PROFILE="GET_PROFILE";
export const PROFILE_LOADING="PROFILE_LOADING";
export const PROFILE_NOT_FOUND="PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE="CLEAR_CURRENT_PROFILE";
export const GET_PROFILES="GET_PROFILES";

export const CREATE_PROFILE_ERROR="CREATE_PROFILE_ERROR";
export const DELETE_USER_FAIL="DELETE_USER_FAIL";